-- Deploy crossfit:crossfit_V1 to pg
BEGIN;

CREATE TABLE "category" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "label" TEXT NOT NULL UNIQUE
);

CREATE TABLE "movement" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "description" TEXT NOT NULL,
    "visual_name" VARCHAR(64) NOT NULL,
    "movement_url" VARCHAR(255),
    "category_id" INT NOT NULL REFERENCES "category"("id")
);

CREATE TABLE "wod" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" TEXT NOT NULL
);

CREATE TABLE "training" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mobility" VARCHAR(255),
    "warm_up" VARCHAR(255),
    "skills" VARCHAR(255),
    "workout" VARCHAR(255),
    "wod_id" INT NOT NULL REFERENCES "wod"("id")
);

CREATE TABLE "box" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "email" TEXT NOT NULL UNIQUE,
    "phone_number" INT NOT NULL UNIQUE,
    "zip_code" INT NOT NULL,
    "city" TEXT NOT NULL
);

COMMIT;