-- Deploy crossfit:crossfit_V1 to pg
BEGIN;

CREATE TABLE "category" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "label" TEXT NOT NULL UNIQUE
);

CREATE TABLE "movement" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "description" TEXT NOT NULL,
    "visual_name" VARCHAR(64) NOT NULL UNIQUE,
    "movement_url" VARCHAR(255) NOT NULL UNIQUE,
    "category_id" INT NOT NULL REFERENCES "category"("id")
);

CREATE TABLE "training" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR(100) NOT NULL UNIQUE,
    "mobility" TEXT NOT NULL,
    "warm_up" TEXT NOT NULL,
    "skills" TEXT NOT NULL,
    "workout" TEXT NOT NULL,
    "category_id" INT NOT NULL REFERENCES "category"("id")
);

CREATE TABLE "box" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "email" TEXT UNIQUE,
    "phone_number" VARCHAR(15) NOT NULL UNIQUE,
    "website" TEXT NOT NULL UNIQUE,
    "zip_code" INT NOT NULL,
    "city" TEXT NOT NULL,
    "category_id" INT NOT NULL REFERENCES "category"("id")
);

COMMIT;